

#ifndef FOOD_ORDERING_SYSTEM_SYSTEMADMINISTRATORSERVICE_H
#define FOOD_ORDERING_SYSTEM_SYSTEMADMINISTRATORSERVICE_H

class SystemAdministratorService {
    public:
    SystemAdministratorService();
};

#endif //FOOD_ORDERING_SYSTEM_SYSTEMADMINISTRATORSERVICE_H